const Strategies = [
"Une ligne a deux côtés",
"Abandonne le désir",
"Abandonne les instructions habituelles",
"Accepte les conseils",
"Accrétion",
"Ajout",
"Autorise un assouplissement (un assouplissement est l’abandon d’une contrainte)",
"Toujours des premiers pas",
"Y a-t-il des sections ?"
Consider transitions",
"Demande aux gens d’aller à l’encontre de leur bon sens",
"Demande à ton corps",
"Sois sale",
"Sois extravagant",
"Sois moins critique plus souvent",
"Respire plus profondément",
"Ponts <ul><li>construire</li><li>brûler</li></ul>",
"Transforme les ambiguïtés en choses spécifiques",
"Ne change rien et continue avec une cohérence impeccable",
"Transforme les spécificités en ambiguïtés",
"Considère les transitions",
"Courage !",
"Coupe une connexion vitale",
"Décore, décore",
"Définis une zone comme 'sûre' et utilise-la comme ancrage",
"Détruis : <ul><li>rien</li><li>la chose la plus importante</li></ul>",
"Abandonne un axiome",
"Auto-indulgence disciplinée",
"Déconnecte-toi du désir",
"Découvre les recettes que tu utilises et abandonne-les",
"Temps déformé",
"Ne fais rien aussi longtemps que possible",
"Fais quelque chose d’ennuyeux",
"Fais quelque chose de soudain, destructeur et imprévisible",
"Fais la dernière chose en premier",
"Les mots ont-ils besoin d’être changés ?",
"Avons-nous besoin de trous ?",
"N’évite pas ce qui est facile",
"N’aie pas peur des choses parce qu’elles sont faciles à faire",
"N’aie pas peur des clichés",
"N’aie pas peur de montrer tes talents",
"Ne brise pas le silence",
"Ne mets pas l’accent sur une chose plus qu’une autre",
"Mets en valeur les différences",
"Mets en valeur les défauts",
"Face à un choix, fais les deux"
<small>(given by Dieter Rot)</small>",
"Trouve une partie sûre et utilise-la comme ancrage",
"Du jardinage, pas de l’architecture",
"Dévoile le jeu",
"Cède à ton pire instinct",
"Va dehors. Ferme la porte",
"Va à un extrême, puis reviens un peu en arrière",
"Va à un extrême, puis retourne à un endroit plus confortable",
"Honore ton erreur comme une intention cachée",
"Comment quelqu’un d’autre s’y prendrait-il ?",
"Comment l’aurais-tu fait ?",
"Humanise quelque chose de sans erreur",
"Dans l’obscurité totale, ou dans une très grande pièce, très silencieusement",
"Est-ce terminé ?",
"Est-ce qu’il manque quelque chose ?",
"Le style est-il le bon ?",
"C’est simplement une question de travail",
"Continue simplement",
"Écoute la voix silencieuse",
"Regarde l’ordre dans lequel tu fais les choses",
"Observe de près les détails les plus embarrassants et amplifie-les",
"Agrandis les détails les plus difficiles",
"Rends un vide précieux en le plaçant dans un cadre exquis",
"Fais une action soudaine, destructrice, imprévisible ; incorpore-la",
"Fais une liste exhaustive de tout ce que tu pourrais faire et fais la dernière chose sur la liste",
"Rends-le plus sensuel",
"Rends quelque chose d’impliqué plus explicite (renforce, duplique)",
"Rends ce qui est parfait plus humain",
"Va vers ce qui est sans importance",
"Ne construis pas un mur, fabrique une brique",
"Une fois que la recherche est en cours, quelque chose sera trouvé",
"Seulement une partie, pas le tout",
"Un seul élément de chaque type",
"Résiste ouvertement au changement",
"Remets en question l’approche héroïque",
"Souviens-toi... de ces soirées tranquilles",
"Supprime une contrainte",
"Supprime les ambiguïtés et transforme-les en choses spécifiques",
"Supprime les spécificités et transforme-les en ambiguïtés",
"La répétition est une forme de changement",
"Retrace tes pas",
"Inverse",
"Court-circuite",
"Soustraction simple",
"Simplement une question de travail",
"Préparation lente, exécution rapide",
"Énonce le problème aussi clairement que possible",
"Fais une pause",
"Retire les éléments dans l’ordre de leur apparente non-importance",
"Retire les éléments importants",
"Le principe d’incohérence",
"La chose la plus importante est celle qu’on oublie le plus facilement",
"Pense <ul><li>à l’intérieur de l’œuvre</li><li>en dehors de l’œuvre</li></ul>",
"Range",
"Vers l’insignifiant",
"Aie confiance en le toi de maintenant",
"Essaie de faire semblant !"
<small>(given by Stewart Brand)</small>",
"Tourne-le à l’envers",
"Utilise des personnes 'non qualifiées'",
"Utilise une vieille idée",
"Utilise une couleur inacceptable",
"Utilise des clichés",
"Utilise des filtres",
"Utilise quelque chose de proche comme modèle",
"Utilise tes propres idées",
"Exprime les soupçons persistants",
"Eau",
"À quoi penses-tu vraiment en ce moment ? Intègre-le",
"Quel contexte semblerait approprié ?",
"Quelle est la solution la plus simple ?",
"Quelles erreurs as-tu commises la dernière fois ?",
"Que faut-il augmenter ? Que faut-il réduire ?",
"Que faut-il maintenir ?",
"Que ferait ton ami le plus proche ?",
"Que ne ferais-tu pas ?",
"C’est pour quand ?",
"Où est la limite ?
Où commence le cadre ?",
"Quels éléments peuvent être regroupés ?",
"Quel cadre rendrait cela juste ?",
"Quel cadre rendrait ceci juste ?",
"Qui devrait faire ce travail ?
Comment s’y prendrait-il ?",
"Travaille à une vitesse différente",
"Est-ce que quelqu’un en voudrait ?",
"Tu es un ingénieur",
"Tu n’as pas à avoir honte d’utiliser tes propres idées",
"Ton erreur était une intention cachée",
Mes idées de stratégies obliques
"inspire toi de internet ou de vidéos créatives",
"gribouille qqch et fait-en un dessin",
"ferme les yeux et laisse faire ton imaginaire",
"dessine qqch le mieux possible mais les yeux fermés",
"fais le contraire de ce qui est demandé",
"dessine qqch sans lever le crayon",
"commence par la fin"

// no comma after the last one!
];
 